name: 'Check CLA'
on:
  pull_request:
    types: [opened]

jobs:
  check_cla:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant GitHub Action
        uses: cla-assistant/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-url: 'https://gist.github.com/VestedKhalid/058d2cc469eed095f98bf83d9baf63f1'
