name: 'Check CLA'
on:
  pull_request:
    types:  [opened, reopened, synchronize]

jobs:
  check_cla:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant GitHub Action
        uses: contributor-assistant/github-action@v2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cla-url: 'https://gist.github.com/LloyAi/9dc9ac3286e8d823e7e7279510b00aca'
